import Link from 'next/link'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body
        className={`antialiased min-h-screen bg-white dark:bg-gray-950 text-gray-900 dark:text-gray-50 ${inter.className}`}
      >
        <div className='max-w-2xl mx-auto py-8 px-4'>
          <header>
            <div className='flex items-center justify-between'>
              <Link href="/" className='text-lg font-bold' >Hacker News Top</Link>
              <nav className='ml-auto text-sm font-medium space-x-6'>
                <Link href='/'>Weekly</Link>
                <Link href='/'>Monthly</Link>
              </nav>
            </div>
          </header>
          <main>{children}</main>
        </div>
      </body>
    </html>
  )
}
